name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE/src/main/kotlin
        if [ ! -z "${{ secrets.NUMBER }}" ]; then
          sed -i "s/20221209/"${{ secrets.NUMBER }}"/" ./Main.kt
        fi
        cd $GITHUB_WORKSPACE
        chmod +x ./gradlew
        ./gradlew jar
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ksugmbot
        path: build/libs/*.jar
        
